name: test-approve-workflow

on:
  pull_request_target:
    types: [opened]

jobs:
  echo-hello-world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Hello world
        run: |
          echo "Hello world"
